# Generated by Django 5.2.16 on 2026-08-29 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Django session key for anonymous users', max_length=40, null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to='legal_documents/')),
                ('document_type', models.CharField(choices=[('auto', 'Auto Detect'), ('fir', 'FIR'), ('legal_notice', 'Legal Notice'), ('agreement', 'Agreement'), ('contract', 'Contract'), ('petition', 'Petition'), ('complaint', 'Complaint'), ('court_order', 'Court Order'), ('judgment', 'Judgment'), ('affidavit', 'Affidavit'), ('bail_application', 'Bail Application'), ('legal_letter', 'Legal Letter'), ('other', 'Other')], default='auto', max_length=30)),
                ('extracted_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('parties', models.JSONField(blank=True, default=list)),
                ('important_dates', models.JSONField(blank=True, default=list)),
                ('legal_references', models.JSONField(blank=True, default=list)),
                ('key_facts', models.JSONField(blank=True, default=list)),
                ('obligations', models.JSONField(blank=True, default=list)),
                ('clauses', models.JSONField(blank=True, default=list)),
                ('deadlines', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('review_points', models.JSONField(blank=True, default=list)),
                ('rag_provisions', models.JSONField(blank=True, default=list, help_text='Related legal provisions from RAG search')),
                ('matched_db_docs', models.JSONField(blank=True, default=list, help_text='LegalDocument IDs matched from legal_references')),
                ('raw_ai_output', models.TextField(blank=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.documentanalysis')),
            ],
        ),
    ]
