# Generated by Django 5.2.16 on 2026-08-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_documentanalysis_documentanalysisresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentanalysis',
            options={},
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysisresult',
            name='clauses',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysisresult',
            name='deadlines',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysisresult',
            name='important_dates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysisresult',
            name='key_facts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysisresult',
            name='legal_references',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysisresult',
            name='matched_db_docs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysisresult',
            name='obligations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysisresult',
            name='parties',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysisresult',
            name='rag_provisions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysisresult',
            name='raw_ai_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysisresult',
            name='review_points',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysisresult',
            name='risks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysisresult',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
