# Generated by Django 5.2.16 on 2026-09-30 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_savedlegaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.documentanalysis'),
        ),
        migrations.AlterField(
            model_name='savedlegaldocument',
            name='legal_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='core.legaldocument'),
        ),
    ]
